### ISSUE TITLE
unzip error

### ISSUE THREAD

**Issue by dirtycomputer** [tg-bomze/Face-Image-Motion-Model#2]
Cloning into 'first_order_model'...
remote: Enumerating objects: 3, done.
remote: Counting objects: 100% (3/3), done.
remote: Compressing objects: 100% (3/3), done.
remote: Total 113 (delta 0), reused 0 (delta 0), pack-reused 110
Receiving objects: 100% (113/113), 58.14 MiB | 25.06 MiB/s, done.
Resolving deltas: 100% (45/45), done.
/content/first_order_model/first_order_model/first_order_model/first_order_model/first_order_model/first_order_model/first_order_model/first_order_model
Downloading...
From: https://drive.google.com/uc?id=1-**************
To: /content/first_order_model/first_order_model/first_order_model/first_order_model/first_order_model/first_order_model/first_order_model/first_order_model/vox-cpk.pth.tar.tar____
729MB [00:03, 220MB/s]
Downloading...
From: https://drive.google.com/uc?id=1o**************
To: /content/first_order_model/first_order_model/first_order_model/first_order_model/first_order_model/first_order_model/first_order_model/first_order_model/shape_predictor_68_face_landmarks.dat.bz2.bz2____
64.0MB [00:00, 176MB/s]
Downloading...
From: https://drive.google.com/uc?id=17**************
To: /content/first_order_model/first_order_model/first_order_model/first_order_model/first_order_model/first_order_model/first_order_model/first_order_model/align.zip.zip____
100% 3.32k/3.32k [00:00<00:00, 2.63MB/s]
unzip:  cannot find or open align.zip, align.zip.zip or align.zip.ZIP.

**Comment by dirtycomputer** [comment]
<img width="1340" alt="截屏2020-03-24下午5 46 33" src="https://user-images.githubusercontent.com/48406770/77411449-6d84f080-6df7-11ea-8940-bb33f8b8f71e.png">

**Comment by tg-bomze** [comment]
https://youtu.be/j9Yq6t4hUeA

**Comment by JamesCullum** [comment]
You can try a different mirror using the Colab from my PR #6 at https://colab.research.google.com/github/JamesCullum/Face-Image-Motion-Model/blob/master/Face_Image_Motion_Model_(Photo_2_Video)_Eng.ipynb
