### ISSUE TITLE
По поводу стайлгана2

### ISSUE THREAD

**Issue by creotiv** [tg-bomze/Face-Image-Motion-Model#3]
Привет,

Слу а ты не видел нигде использования генератора стайл гана для аналогичной задачи?
А то с губами тут проблема большая.. я просто ищу под всякие маркетинговые задачи. Прям с нуля делать самому интересно но сча времени реально ноль(

**Comment by tg-bomze** [comment]
Привет. Можешь попробовать поковыряться в векторах https://rolux.org/media/stylegan2/vectors/ ... тут много разных (в том числе и для коррекции губ)

**Comment by creotiv** [comment]
Пасиб. гляну)
